# =============================================================================
# radiusd.conf — FreeRADIUS 3.x (Docker)
# =============================================================================

prefix      = /usr
exec_prefix = /usr
sysconfdir  = /etc
localstatedir = /var
sbindir     = ${exec_prefix}/sbin
logdir      = /var/log/freeradius
raddbdir    = /etc/freeradius
radacctdir  = ${logdir}/radacct

name        = freeradius

confdir     = ${raddbdir}
modconfdir  = ${confdir}/mods-config
certdir     = ${confdir}/certs
cadir       = ${confdir}/certs
run_dir     = ${localstatedir}/run/${name}
db_dir      = ${raddbdir}

log {
    destination = files
    colourise   = no
    file        = ${logdir}/radius.log
    auth        = yes
    auth_accept = yes
    auth_reject = yes
    auth_badpass = no
    auth_goodpass = no
}

thread pool {
    start_servers       = 5
    max_servers         = 32
    min_spare_servers   = 3
    max_spare_servers   = 10
    max_requests_per_server = 0
    auto_limit_acct     = no
}

max_request_time    = 30
cleanup_delay       = 5
max_requests        = 16384
hostname_lookups    = no

security {
    max_attributes  = 200
    reject_delay    = 1
    status_server   = yes
    allow_vulnerable_openssl = no
}

proxy_requests = no

$INCLUDE clients.conf

modules {
    $INCLUDE mods-enabled/
}

policy {
    $INCLUDE policy.d/
}

$INCLUDE sites-enabled/
